# Generated by Django 3.2.3 on 2021-08-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient_images'),
        ),
    ]
