# Generated by Django 3.2.3 on 2021-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_ingredientmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparemodel',
            name='b_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
